CREATE TABLE RMSE_MAE_EXAMPLE_STAP2_±èÈ¿°ü_1 AS (SELECT ITEM, AVG(ERROR) AS AVG_ERROR FROM RMSE_MAE_EXAMPLE_STEP2 GROUP BY ITEM);

CREATE TABLE RMSE_MAE_EXAMPLE_STAP2_±èÈ¿°ü_2 AS (SELECT YEARWEEK, AVG(ERROR) AS AVG_ERROR FROM RMSE_MAE_EXAMPLE_STEP2 GROUP BY YEARWEEK);



SELECT B.ITEM,
       SQRT(AVG(ABS(B.ERROR))) AS ROOT_ERROR
       FROM (SELECT A.ITEM,A.YEARWEEK,A.QTY,A.PREDICTION ,POWER(ABS(A.QTY-A.PREDICTION),2) AS ERROR FROM RMSE_MAE_EXAMPLE A) B GROUP BY B.ITEM ;
       
       
       

SELECT * FROM CUSTOMERDATA A LEFT JOIN CUSTOMER_NAME B ON A.CUSTID = B.CUSTID ;

SELECT * FROM CUSTOMERDATA A, CUSTOMER_NAME B WHERE A.CUSTID = B.CUSTID(+) ;


SELECT *
from (
SELECT  A.* , B.CUSTNAME 
FROM CUSTOMERDATE A 
RIGHT JOIN CUSTOMER_NAME B
ON A.CUSTID= B.CUSTID)